# Generated by Django 4.2.23 on 2026-06-26 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.IntegerField(blank=True, null=True)),
                ('activity', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_type', models.CharField(blank=True, choices=[('playbook', 'Playbook'), ('poster', 'Poster'), ('asset', 'Asset'), ('logo', 'Logo'), ('video', 'Video')], max_length=50, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('core_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('core_value_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventCoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'event_core_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsEdition',
            fields=[
                ('edition_id', models.AutoField(primary_key=True, serialize=False)),
                ('edition_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'news_editions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_visited', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('engagement_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('visitor_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visitor_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_email', models.EmailField(max_length=255)),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='attendance/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('attendance_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending_verification', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-attendance_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('attendance_open_time', models.DateTimeField(blank=True, null=True)),
                ('attendance_close_time', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('person_in_charge', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('event_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('territory', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('participant_email', models.EmailField(blank=True, db_index=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('source_platform', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('api', 'API')], default='web', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.event')),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('event_id'), name='uniq_lower_email_per_event'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='cms.eventregistration'),
        ),
    ]
