# Generated by Django 4.2.23 on 2026-06-27 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_visitorlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorlog',
            options={'managed': True},
        ),
    ]
