# Generated by Django 4.2.23 on 2026-07-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_event_lifecycle_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': True},
        ),
    ]
