# Generated by Django 4.2.23 on 2026-07-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_genuine_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20, null=True),
        ),
    ]
