# Generated by Django 4.2.23 on 2026-07-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_feedback_is_genuine_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
