# Generated by Django 4.2.23 on 2026-07-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_event_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_feedback_detected',
            field=models.BooleanField(default=False),
        ),
    ]
