# Generated by Django 4.2.29 on 2026-08-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_feedback_is_feedback_detected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
