# Generated by Django 4.2.29 on 2026-08-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_delete_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'managed': True},
        ),
    ]
