# Generated by Django 4.2.29 on 2026-08-05 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='edition',
            field=models.ForeignKey(blank=True, db_column='edition_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='cms.newsedition'),
        ),
    ]
